import type { Metadata } from "next";
import { DM_Sans, Playfair_Display, Quicksand } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers";

const openSans = DM_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const playfair = Quicksand({
  variable: "--font-playfair",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body
          className={`${openSans.variable} ${playfair.variable} antialiased`}
        >
          {children}
        </body>
      </Providers>
    </html>
  );
}
